export const newsFeed = [
  {
    author: "Eliseo Gardner",
    id: 1,
    title: "id labore ex ",
    email: "Eliseo@gardner.biz",
    body: "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor",
  },
  {
    author: "Jayne_Kuhic sydney",
    id: 2,
    title: "quo vero reiciendis ",
    email: "Jayne_Kuhic@sydney.com",
    body: "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at",
  },
  {
    author: "Nikita Garfield ",
    id: 3,
    title: "odio adipisci",
    email: "Nikita@garfield.biz",
    body: "quia molestiae reprehenderit quasi aspernatur\naut expedita occaecati aliquam eveniet laudantium\nomnis ",
  },
  {
    author: "Lew Alysha",
    id: 4,
    title: "alias odio sit",
    email: "Lew@alysha.tv",
    body: "non et atque\noccaecati deserunt quas accusantium unde odit nobis qui voluptatem\nquia voluptas",
  },
  {
    author: "Hayden Althea",
    id: 5,
    title: "vero eaque aliquid ",
    email: "Hayden@althea.biz",
    body: "harum non quasi et ratione\ntempore iure ex voluptates in ratione\nharum architecto ",
  },
  {
    author: "Presley Mueller Myrl",
    id: 6,
    title: "et fugit eligendi",
    email: "Presley.Mueller@myrl.com",
    body: "doloribus at sed quis culpa deserunt consectetur qui praesentium\naccusamus fugiat dicta\nvoluptatem",
  },
  {
    author: "Dallas Ole",
    id: 7,
    title: "repellat consequatur",
    email: "Dallas@ole.me",
    body: "maiores sed dolores similique labore et inventore et\nquasi temporibus esse sunt id et\neos",
  },
  {
    author: "Mallory_Kunze Marie",
    id: 8,
    title: "et omnis dolorem",
    email: "Mallory_Kunze@marie.org",
    body: "ut voluptatem corrupti velit\nad voluptatem maiores\net nisi velit vero accusamus maiores\nvoluptates",
  },
  {
    author: "Meghan_Littel Rene",
    id: 9,
    title: "provident id voluptas",
    email: "Meghan_Littel@rene.us",
    body: "sapiente assumenda molestiae atque\nadipisci laborum distinctio aperiam et ab ut omnis\net",
  },
  {
    author: "Carmen_Keeling Caroline",
    id: 10,
    title: "eaque et deleniti",
    email: "Carmen_Keeling@caroline.name",
    body: "voluptate iusto quis nobis reprehenderit ipsum amet nulla\nquia quas dolores velit et non\naut",
  },
];
